### ISSUE TITLE
Не изменяется dealy.

### ISSUE THREAD

**Issue by glorySyntax** [atomlin-git/trilogy-fastconnect#1]
Создал connect.ini, судя по коду, в правильном месте - в той же директории, где находится сама асишка. Заполнил ини следующим образом: 
[settings]
dealy=50
Ничего не изменилось.

**Comment by atomlin-git** [comment]
конфиг автоматически создаётся по пути:
...\bin\trilogy\Game\Gameface\Binaries\Win64

**Comment by glorySyntax** [comment]
Хорошо, куда тогда кидать tfc.asi?

**Comment by atomlin-git** [comment]
использовать Ultimate ASI Loader, либо по инструкции: https://t.me/TrilogyLoader/55
если юзать аризоновский метод подгрузки, то конфиг будет в папке с дллкой
